/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TourRouteImport } from './routes/tour'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as IndexRouteImport } from './routes/index'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/facilities': typeof FacilitiesRoute
  '/foundation': typeof FoundationRoute
  '/inspiration': typeof InspirationRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/tour': typeof TourRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/facilities': typeof FacilitiesRoute
  '/foundation': typeof FoundationRoute
  '/inspiration': typeof InspirationRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/tour': typeof TourRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/facilities': typeof FacilitiesRoute
  '/foundation': typeof FoundationRoute
  '/inspiration': typeof InspirationRoute
  '/library': typeof LibraryRoute
  '/portal': typeof PortalRoute
  '/tour': typeof TourRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/ai'
    | '/contact'
    | '/disclosure'
    | '/facilities'
    | '/foundation'
    | '/inspiration'
    | '/library'
    | '/portal'
    | '/tour'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/ai'
    | '/contact'
    | '/disclosure'
    | '/facilities'
    | '/foundation'
    | '/inspiration'
    | '/library'
    | '/portal'
    | '/tour'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/ai'
    | '/contact'
    | '/disclosure'
    | '/facilities'
    | '/foundation'
    | '/inspiration'
    | '/library'
    | '/portal'
    | '/tour'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AiRoute: typeof AiRoute
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FoundationRoute: typeof FoundationRoute
  InspirationRoute: typeof InspirationRoute
  LibraryRoute: typeof LibraryRoute
  PortalRoute: typeof PortalRoute
  TourRoute: typeof TourRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  AiRoute: AiRoute,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  FacilitiesRoute: FacilitiesRoute,
  FoundationRoute: FoundationRoute,
  InspirationRoute: InspirationRoute,
  LibraryRoute: LibraryRoute,
  PortalRoute: PortalRoute,
  TourRoute: TourRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
